# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180224_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocr_am_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_am_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_month_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_month_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_pm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_pm_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_yesterday_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocr_yesterday_total',
            field=models.FloatField(default=0),
        ),
    ]
