# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180224_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibi_1', models.FloatField(blank=True, default=0.0, null=True)),
                ('ibi_2', models.FloatField(blank=True, default=0.0, null=True)),
                ('ibi_3', models.FloatField(blank=True, default=0.0, null=True)),
                ('ibi_4', models.FloatField(blank=True, default=0.0, null=True)),
                ('ibi_5', models.FloatField(blank=True, default=0.0, null=True)),
                ('ibi_6', models.FloatField(blank=True, default=0.0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
